# Generated by Django 5.2.9 on 2025-12-18 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Fecha y hora')),
                ('venue_name', models.CharField(default='La Caja Negra', max_length=120, verbose_name='Foro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='events.event')),
            ],
        ),
    ]
